db: 
  root:123123@tcp(127.0.0.1:3306)/timeline?parseTime=True&loc=Local&charset=utf8
port: 
  :9091
secretkey: 
  "123123"
emailuser:
  "1479039156@qq.com"
emailsecret:
  "dtoeddyfqbjsghgg"
emailhost:
  "smtp.qq.com:25"
emailname:
  "TimeLine"
  